#!/usr/bin/env python3
"""Re-export gpt_ckpt.npz -> gpt_weights.h with per-layer pointer tables that
the kernel's gpt.c indexes (T_qkv_w[l], etc.). Standalone (no train_gpt import)."""
import numpy as np

ck = np.load("gpt_ckpt.npz", allow_pickle=True)
chars = str(ck["_chars"])
P = {k: ck[k] for k in ck.files if k != "_chars"}

N_EMBD = int(P["wpe"].shape[1])
BLOCK  = int(P["wpe"].shape[0])
N_LAYER = sum(1 for k in P if k.startswith("qkv_w"))
VOCAB  = len(chars)
PER_LAYER = ["ln1_g", "ln1_b", "qkv_w", "qkv_b", "proj_w", "proj_b",
             "ln2_g", "ln2_b", "fc_w", "fc_b", "mproj_w", "mproj_b"]

def arr(name, a):
    flat = a.reshape(-1).astype(np.float32)
    s = ", ".join(f"{x:.6g}f" for x in flat)
    return f"static const float {name}[{flat.size}] = {{ {s} }};\n"

with open("gpt_weights.h", "w") as f:
    f.write("/* Auto-generated by reexport.py — Astrion on-device char GPT. */\n")
    f.write("#ifndef ASTRION_GPT_WEIGHTS_H\n#define ASTRION_GPT_WEIGHTS_H\n\n")
    f.write(f"#define GPT_VOCAB   {VOCAB}\n#define GPT_BLOCK   {BLOCK}\n")
    f.write(f"#define GPT_NEMBD   {N_EMBD}\n#define GPT_NLAYER  {N_LAYER}\n\n")
    esc = chars.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    f.write(f'static const char gpt_vocab[GPT_VOCAB + 1] = "{esc}";\n\n')
    # non-layer + per-layer weight arrays
    for k in P:
        f.write(arr("w_" + k, P[k]))
    f.write("\n")
    # per-layer pointer tables
    for base in PER_LAYER:
        entries = ", ".join(f"w_{base}{l}" for l in range(N_LAYER))
        f.write(f"static const float* const T_{base}[GPT_NLAYER] = {{ {entries} }};\n")
    f.write("\n#endif\n")

params = sum(v.size for v in P.values())
print(f"exported gpt_weights.h: vocab={VOCAB} block={BLOCK} embd={N_EMBD} "
      f"layers={N_LAYER} params={params} (~{params*4//1024} KB float32)")
