#!/usr/bin/env python3
"""Rasterize Inter into antialiased glyph atlases -> af_font.h for the kernel.
Also renders a preview PNG from the EXTRACTED atlas data (not PIL directly) so
we can verify the atlas is correct before putting it in the kernel."""
from PIL import Image, ImageFont, ImageDraw

TTF = "InterVar.ttf"
FACES = [   # (name, weight-instance, px)
    ("reg13", "Regular",  13),
    ("reg16", "Regular",  16),
    ("sb16",  "SemiBold", 16),
    ("sb30",  "SemiBold", 30),
]
FIRST, LAST = 32, 126

def build_face(weight, px):
    font = ImageFont.truetype(TTF, px)
    font.set_variation_by_name(weight)
    ascent, descent = font.getmetrics()
    line = ascent + descent
    pad = px
    glyphs = []          # (w,h,xoff,yoff,adv, bytes)
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        W = px * 3 + pad * 2
        canvas = Image.new("L", (W, line + pad * 2), 0)
        d = ImageDraw.Draw(canvas)
        penx, peny = pad, pad
        d.text((penx, peny), ch, fill=255, font=font)
        bbox = canvas.getbbox()
        adv = round(font.getlength(ch))
        if bbox is None:                 # space / blank
            glyphs.append((0, 0, 0, 0, adv, b""))
            continue
        x0, y0, x1, y1 = bbox
        g = canvas.crop(bbox)
        glyphs.append((x1 - x0, y1 - y0, x0 - penx, y0 - peny, adv, g.tobytes()))
    return ascent, line, glyphs

def preview(faces):
    """Render a sample from the EXTRACTED data, to verify extraction is right."""
    W, H = 900, 240; img = Image.new("RGB", (W, H), (20, 22, 40)); px = img.load()
    def blit(face, s, ox, oy, col):
        ascent, line, glyphs = face; penx = ox
        for c in s:
            w, h, xoff, yoff, adv, data = glyphs[ord(c) - FIRST]
            for yy in range(h):
                for xx in range(w):
                    a = data[yy * w + xx]
                    if not a: continue
                    X, Y = penx + xoff + xx, oy + yoff + yy
                    if 0 <= X < W and 0 <= Y < H:
                        bg = px[X, Y]
                        px[X, Y] = tuple(int(bg[i] + (col[i]-bg[i]) * a / 255) for i in range(3))
            penx += adv
    blit(faces[3], "Astrion", 30, 20, (255, 255, 255))       # sb30
    blit(faces[1], "The AI-native operating system", 30, 90, (200, 210, 235))  # reg16
    blit(faces[2], "make a file called notes", 30, 130, (255, 255, 255))       # sb16
    blit(faces[0], "on-device - offline - safe by design", 30, 170, (150, 160, 190))  # reg13
    img.save("af_preview.png"); print("wrote af_preview.png")

def emit(faces):
    out = ["/* Auto-generated by gen_font.py - Inter (SIL OFL). Antialiased. */",
           "#ifndef ASTRION_AF_FONT_H", "#define ASTRION_AF_FONT_H", "",
           "typedef struct { unsigned short off; unsigned char w, h;",
           "                 signed char xoff, yoff; unsigned char adv; } af_glyph;",
           "typedef struct { const unsigned char *pix; const af_glyph *glyphs;",
           "                 int first, count, line, ascent; } af_face;", ""]
    names = [f[0] for f in FACES]
    for (name, _, _), (ascent, line, glyphs) in zip(FACES, faces):
        blob = bytearray(); metas = []
        for (w, h, xoff, yoff, adv, data) in glyphs:
            metas.append((len(blob), w, h, xoff, yoff, adv)); blob += data
        hexs = ", ".join(str(b) for b in blob)
        out.append(f"static const unsigned char AF_{name}_pix[{len(blob)}] = {{ {hexs} }};")
        gl = ", ".join(f"{{{o},{w},{h},{xo},{yo},{a}}}" for (o,w,h,xo,yo,a) in metas)
        out.append(f"static const af_glyph AF_{name}_glyphs[{len(metas)}] = {{ {gl} }};")
        out.append("")
    out.append("/* face ids (AF_REG13 ...) live in af.h so this big data header")
    out.append("   is included only by af.c, never by UI files. */")
    out.append("static const af_face af_faces[] = {")
    for (name, _, _), (ascent, line, glyphs) in zip(FACES, faces):
        out.append(f"  {{ AF_{name}_pix, AF_{name}_glyphs, {FIRST}, {LAST-FIRST+1}, {line}, {ascent} }},")
    out.append("};\n#endif")
    open("af_font.h", "w").write("\n".join(out))
    total = sum(len(bytearray().join([g[5] for g in f[2]])) for f in faces)
    print(f"wrote af_font.h: {len(FACES)} faces, ~{total//1024} KB of glyph pixels")

faces = [build_face(w, px) for (_, w, px) in FACES]
preview(faces)
emit(faces)
