/*
 * Astrion v2.0 — transformer forward pass (see include/model.h).
 *
 * A Qwen2 block, ported operation-for-operation from tools/ref_forward.py:
 *
 *     x = x + attn(rmsnorm(x, ln1))     # pre-norm residual
 *     x = x + mlp (rmsnorm(x, ln2))
 *   per layer, then a final rmsnorm and the logit projection.
 *
 * EVERYTHING IS INTEGER. There is no software floating point on x86-64: gcc with
 * -mno-sse lowers a double to x87 (live FPU state), and -mgeneral-regs-only —
 * which the kernel builds with — forbids even that, failing to compile the first
 * double with "SSE register return with SSE disabled." So the whole forward pass
 * is int64 fixed-point at Q8_SCALE_SHIFT (real = fixed / 2^20), the same
 * discipline q8.h follows, and it emits ZERO xmm and needs no XSAVE:
 *
 *   - Heavy matmuls (the four attention projections, three MLP matrices, the
 *     logit head) go through q8_dot (int8) or a __int128 fixed-point dot.
 *   - The transcendentals a GPU would do in float — 1/sqrt for RMSNorm, sin/cos
 *     for RoPE, exp for softmax, sigmoid for SwiGLU — are evaluated here by
 *     integer polynomial in a Q30 working format. Following gpt.c's algorithms
 *     (range-reduce, then a short series), but in fixed-point, not float.
 *
 * Accuracy is bounded by the host test against the float64 oracle: the Q30
 * polynomials are good to ~1e-8 and the Q20 interchange to ~1e-6, so the
 * assembled forward pass matches the oracle to a few 1e-4 — stated and gated in
 * kernel/tests/test_model.c.
 *
 * No allocation, no libc, no kernel headers — every buffer is caller-owned, so
 * the host test exercises this exact source.
 */
#include <stdint.h>
#include "model.h"
#include "q8.h"

unsigned model_ctrl = 0;   /* test-only fault injection; see model.h */

#define SHIFT   Q8_SCALE_SHIFT          /* 20 — the interchange fixed-point */
#define ONE     ((int64_t)1 << SHIFT)   /* 1.0 @ Q20 */
#define HALF    ((int64_t)1 << (SHIFT - 1))

/* ── Q30 working format for the transcendental polynomials ──
 * More fractional bits than the Q20 interchange, so a chain of polynomial
 * multiplies keeps ~1e-8 accuracy. Constants generated by hand from the exact
 * values (tools/ref_forward.py's math), checked in the host test. */
#define FXQ        30
#define FX_ONE     ((int64_t)1 << FXQ)          /* 1.0 @ Q30 */
#define Q30_TO_Q20 (FXQ - SHIFT)                /* 10 */
#define LN2_Q20    726817LL
#define HALFPI_Q20 1647099LL
#define LN2_Q30    744261118LL
#define PI_Q30     3373259426LL
#define TWOPI_Q30  6746518852LL
#define HALFPI_Q30 1686629713LL
#define SQRT2_Q30  1518500250LL

/* exp(-f) = sum_{n} (-1)^n f^n / n!,  n = 0..7,  @Q30 */
static const int64_t EXP_C[8] = {
    1073741824LL, -1073741824LL, 536870912LL, -178956971LL,
    44739243LL, -8947849LL, 1491308LL, -213044LL
};
/* sin(x) coeff on x^(2n): (-1)^n/(2n+1)!,  @Q30 */
static const int64_t SIN_C[6] = {
    1073741824LL, -178956971LL, 8947849LL, -213044LL, 2959LL, -27LL
};
/* ln(m) series S = sum 1/(2n+1) * t^(2n),  @Q30 */
static const int64_t LN_C[7] = {
    1073741824LL, 357913941LL, 214748365LL, 153391689LL,
    119304647LL, 97612893LL, 82595525LL
};

/* ── fixed-point primitives ── */

/* Q30 * Q30 -> Q30. __int128 product keeps the full 60 bits before the shift. */
static inline int64_t qmul(int64_t a, int64_t b)
{
    return (int64_t)(((__int128)a * b) >> FXQ);
}

/* Round a signed Q30 value down to Q20 (or any right shift), to nearest. */
static inline int64_t round_shift(int64_t v, int sh)
{
    int64_t half = (int64_t)1 << (sh - 1);
    return v >= 0 ? (v + half) >> sh : -(((-v) + half) >> sh);
}

/* floor(sqrt(s)) for a non-negative __int128, bit-by-bit and exact. s is always
 * a value whose real square root fits int64 here (see the call sites), so the
 * result never overflows. */
static int64_t fx_isqrt(__int128 s)
{
    if (s <= 0) return 0;
    __int128 res = 0;
    __int128 bit = (__int128)1 << 126;          /* largest even power of two */
    while (bit > s) bit >>= 2;
    while (bit != 0) {
        if (s >= res + bit) { s -= res + bit; res = (res >> 1) + bit; }
        else                  res >>= 1;
        bit >>= 2;
    }
    return (int64_t)res;
}

/* exp(z) for z <= 0, z and result @Q20, result in (0, 1<<SHIFT]. z = -(k*ln2+f)
 * with k>=0 and f in [0,ln2); exp = 2^-k * exp(-f), the series in Q30. */
static int64_t fx_exp_neg(int64_t z)
{
    if (z >= 0) return ONE;                      /* exp(0) = 1 */
    int64_t a = -z;                              /* >= 0, @Q20 */
    int64_t k = a / LN2_Q20;
    int64_t f20 = a - k * LN2_Q20;               /* [0, ln2) @Q20 */
    int sh = Q30_TO_Q20 + (int)k;                /* combined Q30->Q20 and 2^-k */
    if (sh >= 62) return 0;                      /* underflows Q20 */

    int64_t f = f20 << Q30_TO_Q20;               /* @Q30 */
    int64_t acc = EXP_C[7];
    acc = EXP_C[6] + qmul(f, acc);
    acc = EXP_C[5] + qmul(f, acc);
    acc = EXP_C[4] + qmul(f, acc);
    acc = EXP_C[3] + qmul(f, acc);
    acc = EXP_C[2] + qmul(f, acc);
    acc = EXP_C[1] + qmul(f, acc);
    acc = EXP_C[0] + qmul(f, acc);               /* exp(-f) @Q30 in (0.5,1] */
    return (acc + ((int64_t)1 << (sh - 1))) >> sh;
}

/* ln(x) for x > 0, x and result @Q20. x = m*2^e, m folded to [1/sqrt2, sqrt2];
 * ln = e*ln2 + ln(m), ln(m) from the atanh series. Used once, to build RoPE. */
static int64_t fx_ln(int64_t x)
{
    if (x <= 0) return 0;
    int msb = 0;
    for (int64_t t = x; t > 1; t >>= 1) msb++;
    int e = msb - SHIFT;                         /* x_real in [2^e, 2^{e+1}) */
    int msh = FXQ - SHIFT - e;                   /* bring x to m @Q30 in [1,2) */
    int64_t m = msh >= 0 ? (x << msh) : (x >> (-msh));
    if (m > SQRT2_Q30) { m >>= 1; e += 1; }      /* center for a smaller t */

    int64_t t = (int64_t)(((__int128)(m - FX_ONE) << FXQ) / (m + FX_ONE)); /* @Q30 */
    int64_t t2 = qmul(t, t);
    int64_t acc = LN_C[6];
    acc = LN_C[5] + qmul(t2, acc);
    acc = LN_C[4] + qmul(t2, acc);
    acc = LN_C[3] + qmul(t2, acc);
    acc = LN_C[2] + qmul(t2, acc);
    acc = LN_C[1] + qmul(t2, acc);
    acc = LN_C[0] + qmul(t2, acc);
    int64_t lnm = 2 * qmul(t, acc);              /* ln(m) @Q30 */
    return round_shift((int64_t)e * LN2_Q30 + lnm, Q30_TO_Q20);
}

/* sin(a), a and result @Q20. Reduce mod 2pi to [-pi,pi], fold to [-pi/2,pi/2],
 * then the odd Taylor series in Q30. */
static int64_t fx_sin(int64_t a)
{
    int64_t x = a << Q30_TO_Q20;                 /* @Q30 */
    int64_t n = x >= 0 ? (x + PI_Q30) / TWOPI_Q30 : (x - PI_Q30) / TWOPI_Q30;
    x -= n * TWOPI_Q30;                          /* [-pi, pi] @Q30 */
    if (x >  HALFPI_Q30) x =  PI_Q30 - x;        /* fold to [-pi/2, pi/2] */
    if (x < -HALFPI_Q30) x = -PI_Q30 - x;

    int64_t x2 = qmul(x, x);
    int64_t acc = SIN_C[5];
    acc = SIN_C[4] + qmul(x2, acc);
    acc = SIN_C[3] + qmul(x2, acc);
    acc = SIN_C[2] + qmul(x2, acc);
    acc = SIN_C[1] + qmul(x2, acc);
    acc = SIN_C[0] + qmul(x2, acc);
    return round_shift(qmul(x, acc), Q30_TO_Q20);
}

static int64_t fx_cos(int64_t a) { return fx_sin(a + HALFPI_Q20); }  /* cos = sin(a+pi/2) */

/* Plain copies/zeros written so -O2 cannot fold them into a memcpy/memset call:
 * this kernel is freestanding and provides no libc mem* symbols. The volatile
 * destination forces element-wise stores, same guard vmspace.c uses. */
static void mdl_copy(int64_t *dst, const int64_t *src, uint32_t n)
{
    volatile int64_t *d = dst;
    for (uint32_t i = 0; i < n; i++) d[i] = src[i];
}
static void mdl_zero(int64_t *dst, uint32_t n)
{
    volatile int64_t *d = dst;
    for (uint32_t i = 0; i < n; i++) d[i] = 0;
}

/* ── the matmul primitive ──
 *
 * out[rows] = W[rows][cols] . in[nin_real] (+ bias[rows]), everything fixed-point
 * at Q20, the input axis zero-padded from nin_real to W->cols (a Q8_GROUP mult).
 * MODEL_FULL uses int64 fixed-point weights in a __int128 accumulator (no int8
 * loss — the "is the math right" reference); MODEL_Q8 quantizes the activation
 * once and calls q8_dot (adds quantization error). Both return the dot at Q20. */
static void mdl_matmul(struct model_state *st, int64_t *out, const int64_t *in,
                       uint32_t nin_real, const struct model_matrix *W,
                       const int64_t *bias)
{
    uint32_t nin = W->cols, groups = nin / Q8_GROUP;

    if (st->mode == MODEL_Q8) {
        mdl_copy(st->act_fix, in, nin_real);              /* padded contiguous copy */
        if (nin > nin_real) mdl_zero(st->act_fix + nin_real, nin - nin_real);
        q8_quantize(st->act_fix, nin, st->act_q, st->act_qg);
        for (uint32_t j = 0; j < W->rows; j++) {
            int64_t dot = q8_dot(W->q  + (uint64_t)j * nin,
                                 W->qg + (uint64_t)j * groups,
                                 st->act_q, st->act_qg, nin);
            out[j] = bias ? dot + bias[j] : dot;
        }
    } else {
        for (uint32_t j = 0; j < W->rows; j++) {
            const int64_t *wr = W->full + (uint64_t)j * nin;
            __int128 acc = 0;
            for (uint32_t i = 0; i < nin_real; i++)       /* pad cols are zero */
                acc += (__int128)wr[i] * (__int128)in[i];
            acc += (__int128)HALF;                        /* round, not truncate */
            int64_t dot = (int64_t)(acc >> SHIFT);
            out[j] = bias ? dot + bias[j] : dot;
        }
    }
}

/* ── the ops ── */

/* RMSNorm: out = x / sqrt(mean(x^2) + eps) * weight. No mean subtraction — the
 * LayerNorm difference the port must not reintroduce. Everything integer:
 * mean(x^2)+eps is @Q40, its isqrt is the RMS @Q20, and 2^40/RMS is 1/RMS @Q20. */
/* RMSNorm over `n` elements. One implementation, called both for the residual
 * stream (n = dim) and for QK-norm (n = head_dim) — a second copy sized to
 * head_dim would be one more place for the fixed-point rounding to drift.
 * Safe in place (out == in): the sum-of-squares is taken over all of `in`
 * before any element of `out` is written. */
static void mdl_rmsnorm_n(const struct model_config *cfg, int64_t *out,
                          const int64_t *in, const int64_t *weight, uint32_t n)
{
    __int128 ss = 0;
    for (uint32_t i = 0; i < n; i++) ss += (__int128)in[i] * in[i];   /* @Q40 */
    __int128 M = ss / n + cfg->rms_eps_fp;                            /* @Q40 (eps @Q40) */
    int64_t rms = fx_isqrt(M);                                       /* RMS @Q20 */
    if (rms <= 0) rms = 1;
    int64_t inv = (int64_t)(((__int128)1 << (2 * SHIFT)) / rms);      /* 1/RMS @Q20 */

    for (uint32_t i = 0; i < n; i++) {
        __int128 p = (__int128)in[i] * inv;      /* @Q40 */
        p = p * weight[i];                        /* @Q60 */
        p += (__int128)1 << (2 * SHIFT - 1);      /* round the >>40 */
        out[i] = (int64_t)(p >> (2 * SHIFT));
    }
}

static void mdl_rmsnorm(const struct model_config *cfg, int64_t *out,
                        const int64_t *in, const int64_t *weight)
{
    mdl_rmsnorm_n(cfg, out, in, weight, cfg->dim);
}

/* RoPE on one head_dim slice: rotate each adjacent (2i, 2i+1) pair by
 * pos*inv_freq[i]. Adjacent-pair convention, matching the oracle and converter. */
static void mdl_rope(struct model_state *st, const struct model_config *cfg,
                     int64_t *vec, uint32_t pos)
{
    uint32_t half = cfg->head_dim / 2;
    for (uint32_t i = 0; i < half; i++) {
        int64_t ang = (int64_t)pos * st->inv_freq[i];    /* @Q20 */
        int64_t c = fx_cos(ang), s = fx_sin(ang);        /* @Q20 */
        int64_t a = vec[2 * i], b = vec[2 * i + 1];
        __int128 nx = (__int128)a * c - (__int128)b * s;
        __int128 ny = (__int128)a * s + (__int128)b * c;
        vec[2 * i]     = (int64_t)((nx + HALF) >> SHIFT);
        vec[2 * i + 1] = (int64_t)((ny + HALF) >> SHIFT);
    }
}

void model_rope_init(struct model_state *st, const struct model_config *cfg)
{
    uint32_t half = cfg->head_dim / 2;
    int64_t lnth = fx_ln((int64_t)cfg->rope_theta << SHIFT);      /* ln(theta) @Q20 */
    for (uint32_t i = 0; i < half; i++) {
        int64_t arg = -((int64_t)(2 * i) * lnth) / (int64_t)cfg->head_dim;  /* <=0 @Q20 */
        st->inv_freq[i] = fx_exp_neg(arg);                       /* theta^(-2i/hd) @Q20 */
    }
}

/* Grouped-query attention for one token at st->pos. Q/K/V are projected, RoPE'd
 * (Q and K only), K/V written straight into the cache slot, then each Q head
 * softmax-attends over its shared KV head across cached positions 0..pos. */
static void mdl_attention(const struct model_weights *w, struct model_state *st,
                          uint32_t l, const int64_t *xn, int64_t *out)
{
    const struct model_config *cfg = &w->cfg;
    const struct model_layer *L = &w->layers[l];
    uint32_t H = cfg->n_heads, KV = cfg->n_kv_heads, HD = cfg->head_dim;
    uint32_t D = cfg->dim, group = H / KV, pos = st->pos;
    uint64_t kvrow = (uint64_t)KV * HD;
    uint64_t base  = ((uint64_t)l * cfg->max_seq + pos) * kvrow;
    int64_t *kdst = st->kcache + base;
    int64_t *vdst = st->vcache + base;

    mdl_matmul(st, st->q, xn, D, &L->wq, L->bq);
    mdl_matmul(st, kdst,  xn, D, &L->wk, L->bk);
    mdl_matmul(st, vdst,  xn, D, &L->wv, L->bv);

    /* QK-norm: RMSNorm each Q and K head over head_dim, BEFORE RoPE, with one
     * shared gain (Ember/Qwen3; off for Qwen2). Ordering matters — normalize
     * then rotate, matching the oracle (ref_forward.py) and the converter, or a
     * qk-normed model silently attends wrong. In place: each head is its own
     * contiguous HD slice. */
    if (cfg->qk_norm) {
        for (uint32_t h = 0; h < H;  h++)
            mdl_rmsnorm_n(cfg, st->q + (uint64_t)h * HD, st->q + (uint64_t)h * HD, L->qk_g, HD);
        for (uint32_t h = 0; h < KV; h++)
            mdl_rmsnorm_n(cfg, kdst + (uint64_t)h * HD, kdst + (uint64_t)h * HD, L->qk_g, HD);
    }

    if (!(model_ctrl & MODEL_CTRL_NO_ROPE)) {
        for (uint32_t h = 0; h < H;  h++) mdl_rope(st, cfg, st->q + (uint64_t)h * HD, pos);
        for (uint32_t h = 0; h < KV; h++) mdl_rope(st, cfg, kdst  + (uint64_t)h * HD, pos);
    }
    if (st->trace) {
        mdl_copy(st->trace->qrope + (uint64_t)l * H  * HD, st->q, H  * HD);
        mdl_copy(st->trace->krope + (uint64_t)l * KV * HD, kdst,  KV * HD);
    }

    int64_t scale = (int64_t)(((__int128)1 << (2 * SHIFT)) / fx_isqrt((__int128)HD << (2 * SHIFT)));
    for (uint32_t h = 0; h < H; h++) {
        uint32_t kvh = (model_ctrl & MODEL_CTRL_GQA_MISGROUP) ? (h % KV) : (h / group);
        const int64_t *qh = st->q + (uint64_t)h * HD;

        int64_t mx = INT64_MIN;
        for (uint32_t t = 0; t <= pos; t++) {
            const int64_t *kt = st->kcache + ((uint64_t)l * cfg->max_seq + t) * kvrow
                                           + (uint64_t)kvh * HD;
            __int128 dot = 0;
            for (uint32_t d = 0; d < HD; d++) dot += (__int128)qh[d] * kt[d];   /* @Q40 */
            int64_t s = (int64_t)((dot * scale) >> (2 * SHIFT));                /* *scale @Q20 */
            st->scores[t] = s;
            if (s > mx) mx = s;
        }
        int64_t sum = 0;
        for (uint32_t t = 0; t <= pos; t++) {
            int64_t e = fx_exp_neg(st->scores[t] - mx);      /* scores-mx <= 0 */
            st->scores[t] = e;
            sum += e;
        }
        if (sum <= 0) sum = 1;

        int64_t *oh = st->heads + (uint64_t)h * HD;
        for (uint32_t d = 0; d < HD; d++) {
            __int128 acc = 0;
            for (uint32_t t = 0; t <= pos; t++) {
                const int64_t *vt = st->vcache + ((uint64_t)l * cfg->max_seq + t) * kvrow
                                               + (uint64_t)kvh * HD;
                acc += (__int128)st->scores[t] * vt[d];      /* @Q40 */
            }
            oh[d] = (int64_t)(acc / sum);                    /* @Q40 / @Q20 -> @Q20 */
        }
    }

    mdl_matmul(st, out, st->heads, H * HD, &L->wo, 0);
}

/* SwiGLU MLP: down( silu(gate(x)) * up(x) ). silu(z) = z * sigmoid(z), and
 * sigmoid is computed from exp of a non-positive argument for numerical safety. */
static void mdl_mlp(const struct model_weights *w, struct model_state *st,
                    uint32_t l, const int64_t *xn, int64_t *out)
{
    const struct model_config *cfg = &w->cfg;
    const struct model_layer *L = &w->layers[l];
    uint32_t D = cfg->dim, F = cfg->ffn_dim;

    mdl_matmul(st, st->ff1, xn, D, &L->w_gate, 0);
    mdl_matmul(st, st->ff2, xn, D, &L->w_up,   0);
    for (uint32_t i = 0; i < F; i++) {
        int64_t g = st->ff1[i];
        int64_t sig;
        if (g >= 0) {                            /* sigmoid = 1/(1+e^-g) */
            int64_t e = fx_exp_neg(-g);
            sig = (int64_t)(((__int128)ONE << SHIFT) / (ONE + e));
        } else {                                 /* sigmoid = e^g/(1+e^g) */
            int64_t e = fx_exp_neg(g);
            sig = (int64_t)(((__int128)e << SHIFT) / (ONE + e));
        }
        int64_t silu = (int64_t)(((__int128)g * sig) >> SHIFT);
        st->ff1[i]   = (int64_t)(((__int128)silu * st->ff2[i]) >> SHIFT);
    }
    mdl_matmul(st, out, st->ff1, F, &L->w_down, 0);
}

/* One decode step, mirroring the oracle's forward() body exactly. */
void model_forward(const struct model_weights *w, struct model_state *st,
                   uint32_t token, int64_t *logits)
{
    const struct model_config *cfg = &w->cfg;
    uint32_t D = cfg->dim;

    /* The KV cache holds exactly max_seq positions; writing slot `pos` past that
     * would run off the end. Refuse rather than corrupt — the caller owns the
     * decode-length policy (stop or slide) and must keep pos < max_seq. */
    if (st->pos >= cfg->max_seq) return;

    mdl_copy(st->x, w->embed + (uint64_t)token * D, D);

    for (uint32_t l = 0; l < cfg->n_layers; l++) {
        mdl_rmsnorm(cfg, st->xn, st->x, w->layers[l].ln1);
        if (st->trace) mdl_copy(st->trace->ln1 + (uint64_t)l * D, st->xn, D);

        mdl_attention(w, st, l, st->xn, st->tmp);
        if (st->trace) mdl_copy(st->trace->attn + (uint64_t)l * D, st->tmp, D);
        if (!(model_ctrl & MODEL_CTRL_NO_RESIDUAL))
            for (uint32_t i = 0; i < D; i++) st->x[i] += st->tmp[i];

        mdl_rmsnorm(cfg, st->xn, st->x, w->layers[l].ln2);
        if (st->trace) mdl_copy(st->trace->ln2 + (uint64_t)l * D, st->xn, D);

        mdl_mlp(w, st, l, st->xn, st->tmp);
        if (st->trace) mdl_copy(st->trace->mlp + (uint64_t)l * D, st->tmp, D);
        if (!(model_ctrl & MODEL_CTRL_NO_RESIDUAL))
            for (uint32_t i = 0; i < D; i++) st->x[i] += st->tmp[i];

        if (st->trace) mdl_copy(st->trace->xout + (uint64_t)l * D, st->x, D);
    }

    mdl_rmsnorm(cfg, st->xn, st->x, w->final_ln);
    if (st->trace) mdl_copy(st->trace->final_norm, st->xn, D);

    mdl_matmul(st, logits, st->xn, D, &w->lm_head, 0);
    st->pos++;
}

uint32_t model_argmax(const int64_t *logits, uint32_t vocab)
{
    /* Strict '>' so a tie keeps the earlier (lower) index — the deterministic
     * tie-break the header promises. A '>=' here would silently prefer the
     * LAST of equal logits, which no test with distinct random logits would
     * catch and which would make greedy decode depend on scan direction. */
    uint32_t best = 0;
    for (uint32_t i = 1; i < vocab; i++)
        if (logits[i] > logits[best]) best = i;
    return best;
}
