/* Gate for the tokenizer's GPT-2 mode — tok.c against tiktoken's "gpt2"
 * encoding, which is what Ember is trained and chatted with.
 *
 * Ember is a GPT-2-tokenized model (custom-model/train_best.py: tiktoken gpt2,
 * vocab 50257, <|endoftext|> 50256). Until this mode existed the kernel ran
 * every table under Qwen's split — "2025" as four digit tokens where GPT-2
 * makes two, "DON'T" as one contraction where GPT-2 makes three pieces — and a
 * model fed ids it never saw reads as a bad model, not a broken tokenizer. QEMU
 * cannot see the difference; this can. Same shape as test_tok.c: it #includes
 * the freestanding engine as one TU, so it exercises the EXACT source the
 * kernel ships.
 *
 * SIX gates:
 *   1. REFERENCE DIFF (the real one). Over a corpus aimed at every place the
 *      GPT-2 split differs from Qwen's, tok_encode in gpt2 mode reproduces the
 *      ids tiktoken produces. Tier 1 runs always, against a small embedded
 *      subset table (real ids remapped by one bijection, so it proves EXACT
 *      segmentation + merge order). Tier 2 runs when TOK_GPT2_BIN points at the
 *      full table from `mktok.py --gpt2` and matches the LITERAL tiktoken ids.
 *   2. ROUND-TRIP. encode then decode returns the original bytes.
 *   3. CONTROL. Corrupt one merge rank; the diff must diverge.
 *   4. THE KIND IS LOAD-BEARING. The same table encoded under the Qwen split
 *      must DIFFER on a digit string — proving the header's kind actually
 *      selects the pretokenizer rather than being decoration.
 *   5. SINGLETON PAIRING. tok_set_kind refuses a kind the table did not
 *      declare (a Qwen brain in front of this table), accepts the matching one,
 *      and a legacy kind-0 table accepts either.
 *   6. MALFORMED. A kind the kernel does not know is rejected at parse.
 *
 *   cc -std=c11 -Wall -Wextra -Werror -Iinclude tests/test_tok_gpt2.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "tok.h"
#include "../src/tok.c"                     /* the engine under test, as one TU */
#include "../tools/tok_gpt2_fixture.h"      /* GENERATED by tools/tok_gpt2_ref.py */

static int failures;

static int ids_equal(const uint32_t *got, int ngot, const unsigned *want, int nwant) {
    if (ngot != nwant) return 0;
    for (int i = 0; i < ngot; i++)
        if (got[i] != want[i]) return 0;
    return 1;
}

static void show_ids(const uint32_t *ids, int n) {
    printf("[");
    for (int i = 0; i < n; i++) printf("%s%u", i ? " " : "", ids[i]);
    printf("]");
}

int main(void) {
    printf("tokenizer gate (gpt2) — tok.c vs tiktoken gpt2 (Ember's tokenizer), ASCII corpus\n");
    printf("corpus: %d strings; subset table %d bytes\n\n", TOK_G2_REF_N, TOK_G2_TABLE_LEN);

    struct tok_table T;
    const char *pe = tok_parse(TOK_G2_TABLE, TOK_G2_TABLE_LEN, &T);
    if (pe) {
        printf("FAIL parse embedded table: %s\n\nfailures  1\nFAILED\n", pe);
        return 1;
    }
    printf("parse      embedded table ok: %u tokens, %u merges, blob %u B, kind %u\n",
           T.n_tokens, T.n_merges, T.blob_len, T.kind);
    if (T.kind != TOK_KIND_GPT2) { printf("  FAIL header kind is %u, want %u\n", T.kind, TOK_KIND_GPT2); failures++; }

    /* ── 1. REFERENCE DIFF, tier 1 (remapped tiktoken ids) ── */
    {
        int ok = 0; long toks = 0;
        for (int i = 0; i < TOK_G2_REF_N; i++) {
            uint32_t ids[256];
            int n = tok_encode_tab(&T, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], ids, 256);
            if (n >= 0 && ids_equal(ids, n, TOK_G2_REF_IDS[i], TOK_G2_REF_NID[i])) { ok++; toks += n; }
            else {
                if (failures < 8) {
                    printf("  MISMATCH str %d %s: got ", i, TOK_G2_REF_STR[i]);
                    show_ids(ids, n); printf(" want %d ids\n", TOK_G2_REF_NID[i]);
                }
                failures++;
            }
        }
        if (ok == TOK_G2_REF_N)
            printf("ref-diff   TIER 1: all %d strings match tiktoken gpt2 (%ld tokens, remapped ids)\n",
                   TOK_G2_REF_N, toks);
        else
            printf("  FAIL ref-diff tier 1: %d/%d strings matched\n", ok, TOK_G2_REF_N);
    }

    /* ── 2. ROUND-TRIP ── */
    {
        int ok = 0;
        for (int i = 0; i < TOK_G2_REF_N; i++) {
            uint32_t ids[256];
            uint8_t back[1024];
            int n = tok_encode_tab(&T, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], ids, 256);
            int m = tok_decode_tab(&T, ids, (uint32_t)n, back, sizeof back);
            if (n >= 0 && m == TOK_G2_REF_STRLEN[i] &&
                memcmp(back, TOK_G2_REF_STR[i], (size_t)m) == 0) ok++;
            else {
                if (failures < 8) printf("  ROUND-TRIP FAIL str %d: %d bytes back, want %d\n",
                                         i, m, TOK_G2_REF_STRLEN[i]);
                failures++;
            }
        }
        if (ok == TOK_G2_REF_N)
            printf("round-trip decode(encode(s)) == s for all %d strings\n", TOK_G2_REF_N);
    }

    /* ── 3. CONTROL: corrupt one merge rank; the diff must catch it ── */
    {
        unsigned char *bad = malloc(TOK_G2_TABLE_LEN);
        memcpy(bad, TOK_G2_TABLE, TOK_G2_TABLE_LEN);
        bad[TOK_G2_REF_CTRL_RANK_OFF + 0] = 0xFF; bad[TOK_G2_REF_CTRL_RANK_OFF + 1] = 0xFF;
        bad[TOK_G2_REF_CTRL_RANK_OFF + 2] = 0xFF; bad[TOK_G2_REF_CTRL_RANK_OFF + 3] = 0xFF;
        struct tok_table B;
        const char *be = tok_parse(bad, TOK_G2_TABLE_LEN, &B);
        if (be) { printf("  FAIL control: corrupted table did not parse (%s)\n", be); failures++; }
        else {
            int i = TOK_G2_REF_CTRL_STR;
            uint32_t ids[256];
            int n = tok_encode_tab(&B, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], ids, 256);
            if (ids_equal(ids, n, TOK_G2_REF_IDS[i], TOK_G2_REF_NID[i])) {
                printf("  FAIL control: corrupting a merge rank did NOT change str %d\n", i); failures++;
            } else
                printf("control    corrupt 1 merge rank -> str %d re-tokenizes (%d ids vs %d): gate catches it\n",
                       i, n, TOK_G2_REF_NID[i]);
        }
        free(bad);
    }

    /* ── 4. THE KIND IS LOAD-BEARING: the Qwen split must give different ids ──
     * Same table, kind flipped to qwen2 in the view: "the year is 2025 already"
     * must come out differently (Qwen splits the digits one per pretoken and
     * they can never merge). If it did not differ, the kind field would be
     * decoration and a Qwen brain paired with this table would go unnoticed. */
    {
        int i = -1;
        for (int k = 0; k < TOK_G2_REF_N; k++)
            if (strstr(TOK_G2_REF_STR[k], "2025")) { i = k; break; }
        if (i < 0) { printf("  FAIL kind test: corpus has no digit-run string\n"); failures++; }
        else {
            struct tok_table Q = T;
            Q.kind = TOK_KIND_QWEN2;
            uint32_t g[256], q[256];
            int ng = tok_encode_tab(&T, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], g, 256);
            int nq = tok_encode_tab(&Q, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], q, 256);
            int same = (ng == nq) && memcmp(g, q, (size_t)ng * sizeof g[0]) == 0;
            if (same) { printf("  FAIL kind: gpt2 and qwen2 splits gave the same ids for str %d\n", i); failures++; }
            else printf("kind       same table, qwen2 split -> str %d differs (%d vs %d ids): the kind selects the split\n",
                        i, nq, ng);
        }
    }

    /* ── 5. SINGLETON PAIRING via tok_init/tok_set_kind ── */
    {
        const char *ie = tok_init(TOK_G2_TABLE, TOK_G2_TABLE_LEN);
        if (ie) { printf("  FAIL tok_init: %s\n", ie); failures++; }
        else {
            int bad_pair = tok_set_kind(TOK_KIND_QWEN2);      /* Qwen brain, GPT-2 table */
            int good_pair = tok_set_kind(TOK_KIND_GPT2);
            int unknown = tok_set_kind(9u);
            if (bad_pair != -1 || good_pair != 0 || unknown != -1 || tok_kind() != TOK_KIND_GPT2) {
                printf("  FAIL pairing: qwen2->%d gpt2->%d unknown->%d kind now %u\n",
                       bad_pair, good_pair, unknown, tok_kind());
                failures++;
            } else printf("pairing    table says gpt2: brain qwen2 refused, gpt2 accepted, unknown refused\n");

            /* the encoder through the singleton is the gpt2 one */
            uint32_t ids[256];
            int i = TOK_G2_REF_CTRL_STR;
            int n = tok_encode(TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], ids, 256);
            if (!ids_equal(ids, n, TOK_G2_REF_IDS[i], TOK_G2_REF_NID[i])) {
                printf("  FAIL singleton encode differs from the table encode\n"); failures++;
            }
        }
        /* a legacy table (kind 0 in the header) accepts either kind */
        unsigned char *legacy = malloc(TOK_G2_TABLE_LEN);
        memcpy(legacy, TOK_G2_TABLE, TOK_G2_TABLE_LEN);
        legacy[32] = 0; legacy[33] = 0; legacy[34] = 0; legacy[35] = 0;
        const char *le = tok_init(legacy, TOK_G2_TABLE_LEN);
        if (le) { printf("  FAIL legacy tok_init: %s\n", le); failures++; }
        else if (tok_kind() != TOK_KIND_UNSPEC || tok_set_kind(TOK_KIND_GPT2) != 0 || tok_kind() != TOK_KIND_GPT2) {
            printf("  FAIL legacy table did not accept a brain's kind\n"); failures++;
        } else printf("pairing    legacy kind-0 table: takes the brain's kind (gpt2)\n");
        free(legacy);
    }

    /* ── 6. MALFORMED: an unknown kind is rejected at parse ── */
    {
        unsigned char *m = malloc(TOK_G2_TABLE_LEN);
        memcpy(m, TOK_G2_TABLE, TOK_G2_TABLE_LEN);
        m[32] = 3;
        struct tok_table X;
        const char *xe = tok_parse(m, TOK_G2_TABLE_LEN, &X);
        if (!xe || strcmp(xe, "bad tokenizer kind") != 0 || X.base) {
            printf("  FAIL malformed kind: %s\n", xe ? xe : "accepted"); failures++;
        } else printf("reject     kind 3                 -> \"%s\"\n", xe);
        free(m);
    }

    /* ── 1b. REFERENCE DIFF, tier 2 (LITERAL tiktoken ids, the full table) ── */
    {
        const char *bin = getenv("TOK_GPT2_BIN");
        if (!bin) {
            printf("ref-diff   TIER 2: SKIPPED (set TOK_GPT2_BIN to the table from\n"
                   "           `mktok.py --gpt2` to match the LITERAL tiktoken ids over\n"
                   "           the full %d-token table)\n", TOK_G2_REAL_VOCAB);
        } else {
            FILE *fp = fopen(bin, "rb");
            if (!fp) { printf("  FAIL tier 2: cannot open %s\n", bin); failures++; }
            else {
                fseek(fp, 0, SEEK_END); long sz = ftell(fp); fseek(fp, 0, SEEK_SET);
                unsigned char *buf = malloc((size_t)sz);
                if (fread(buf, 1, (size_t)sz, fp) != (size_t)sz) { printf("  FAIL tier 2: short read\n"); failures++; }
                else {
                    struct tok_table R;
                    const char *re = tok_parse(buf, (uint32_t)sz, &R);
                    if (re) { printf("  FAIL tier 2: full table rejected: %s\n", re); failures++; }
                    else if (R.kind != TOK_KIND_GPT2 || R.n_tokens != TOK_G2_REAL_VOCAB) {
                        printf("  FAIL tier 2: table kind %u vocab %u, want gpt2/%d\n", R.kind, R.n_tokens, TOK_G2_REAL_VOCAB);
                        failures++;
                    } else {
                        int ok = 0; long toks = 0;
                        for (int i = 0; i < TOK_G2_REF_N; i++) {
                            uint32_t idbuf[256];
                            int n = tok_encode_tab(&R, TOK_G2_REF_STR[i], (uint32_t)TOK_G2_REF_STRLEN[i], idbuf, 256);
                            if (n >= 0 && ids_equal(idbuf, n, TOK_G2_REAL_IDS[i], TOK_G2_REAL_NID[i])) { ok++; toks += n; }
                            else {
                                if (failures < 8) {
                                    printf("  TIER2 MISMATCH str %d %s: got ", i, TOK_G2_REF_STR[i]);
                                    show_ids(idbuf, n); printf(" want %d ids\n", TOK_G2_REAL_NID[i]);
                                }
                                failures++;
                            }
                        }
                        /* the eot token decodes to its text and never comes out of encode */
                        uint32_t eot = TOK_G2_REAL_EOT;
                        uint8_t txt[32];
                        int m = tok_decode_tab(&R, &eot, 1, txt, sizeof txt);
                        if (m != 13 || memcmp(txt, "<|endoftext|>", 13) != 0) {
                            printf("  FAIL tier 2: eot %u decodes to %d bytes, want <|endoftext|>\n", eot, m); failures++;
                        }
                        if (ok == TOK_G2_REF_N)
                            printf("ref-diff   TIER 2: all %d strings match LITERAL tiktoken ids "
                                   "(%ld tokens, full table: %u tokens/%u merges; eot %u decodes)\n",
                                   TOK_G2_REF_N, toks, R.n_tokens, R.n_merges, eot);
                    }
                }
                free(buf); fclose(fp);
            }
        }
    }

    printf("\nfailures  %d\n", failures);
    printf(failures ? "FAILED\n" : "PASS\n");
    return failures ? 1 : 0;
}
