/* Gate for the byte-level BPE tokenizer — tok.c against the real Qwen2.5
 * tokenizer via the HuggingFace `tokenizers` library.
 *
 * QEMU cannot tell a correct tokenizer from one that is off by a token, and a
 * tokenizer that is off by a token feeds the model garbage that reads as a bad
 * model — the failure mode that costs a week. So this is a host test, the same
 * discipline q8_dot and the forward pass met. It #includes the freestanding
 * engine as one TU, so it exercises the EXACT source the kernel ships.
 *
 * FIVE gates:
 *   1. REFERENCE DIFF (the real one). For a corpus of ASCII strings, assert
 *      tok_encode reproduces the ids the HF `tokenizers` library produces for
 *      the real Qwen2.5 tokenizer. Tier 1 runs always, against a small embedded
 *      subset table whose ids are the real ids remapped by one bijection (so it
 *      proves EXACT segmentation + merge-order parity with Qwen). Tier 2 runs
 *      when TOK_REAL_DIR points at the real 4 MB tok.bin, and matches the LITERAL
 *      real Qwen ids over the full merge table.
 *   2. ROUND-TRIP. encode then decode returns the original bytes, over the corpus.
 *   3. CONTROL. Corrupt one merge rank in a copy of the table; the reference diff
 *      for that string must then diverge — a gate that cannot fail is not a gate.
 *   4. MALFORMED TABLES. truncated / backwards-offset / bad-magic / bad-version /
 *      out-of-range each return failure and read nothing past the buffer (run the
 *      binary under -fsanitize=address to prove the second half).
 *   5. max/truncation contract. encode into a short buffer drops the tail at a
 *      segment boundary rather than half-encoding.
 *
 * ASCII ONLY, STATED. kbd.c is a 128-entry US table and the serial path
 * allow-lists 0x20..0x7E, so non-ASCII cannot be entered. The corpus is
 * therefore ASCII, and Qwen's NFC normalizer is the identity on ASCII — so this
 * gate does NOT exercise or claim Unicode coverage. Bytes >= 0x80 are handled by
 * tok.c as "other" (self-consistent, safe, but not the Unicode reference).
 *
 *   cc -std=c11 -Wall -Wextra -Werror -Iinclude tests/test_tok.c
 *   ...and, for gate 4's second half:
 *   cc -std=c11 -fsanitize=address -Iinclude tests/test_tok.c && ./a.out
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "tok.h"
#include "../src/tok.c"                 /* the engine under test, as one TU */
#include "../tools/tok_ref_fixture.h"   /* GENERATED by tools/tok_ref.py */

static int failures;

static uint32_t rd32le(const unsigned char *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

/* Compare an encode result to an expected id list. Returns 1 on match. */
static int ids_equal(const uint32_t *got, int ngot, const unsigned *want, int nwant) {
    if (ngot != nwant) return 0;
    for (int i = 0; i < ngot; i++)
        if (got[i] != want[i]) return 0;
    return 1;
}

/* Assert a malformed table is rejected AND leaves the out-view zeroed. The
 * buffer is malloc'd to EXACTLY `len` so ASan's redzone catches any read past
 * the end — that is how "reads nothing past the buffer" is proven, not asserted. */
static void expect_reject(const char *what, const unsigned char *bytes, uint32_t len) {
    unsigned char *buf = malloc(len ? len : 1);
    memcpy(buf, bytes, len);
    struct tok_table t;
    const char *e = tok_parse(buf, len, &t);
    if (!e) {
        printf("  FAIL malformed(%s): parse SUCCEEDED, should have failed\n", what);
        failures++;
    } else if (t.base || t.n_tokens || t.n_merges || t.merges || t.offsets || t.blob) {
        printf("  FAIL malformed(%s): rejected but left a non-zero view\n", what);
        failures++;
    } else {
        printf("  reject  %-22s -> \"%s\"\n", what, e);
    }
    free(buf);
}

int main(void) {
    printf("tokenizer gate — tok.c vs real Qwen2.5 (HF tokenizers), ASCII corpus\n");
    printf("corpus: %d strings; subset table %d bytes\n\n", TOK_REF_N, TOK_TABLE_LEN);

    /* ── parse the embedded subset table ── */
    struct tok_table T;
    const char *pe = tok_parse(TOK_TABLE, TOK_TABLE_LEN, &T);
    if (pe) {
        printf("FAIL parse embedded table: %s\n", pe);
        printf("\nfailures  1\nFAILED\n");
        return 1;
    }
    printf("parse      embedded table ok: %u tokens, %u merges, blob %u B\n",
           T.n_tokens, T.n_merges, T.blob_len);

    /* ── 1. REFERENCE DIFF, tier 1 (remapped real Qwen ids) ── */
    {
        int ok = 0; long toks = 0;
        for (int i = 0; i < TOK_REF_N; i++) {
            uint32_t ids[256];
            int n = tok_encode_tab(&T, TOK_REF_STR[i], (uint32_t)TOK_REF_STRLEN[i], ids, 256);
            if (n >= 0 && ids_equal(ids, n, TOK_REF_IDS[i], TOK_REF_NID[i])) { ok++; toks += n; }
            else {
                if (failures < 6) printf("  MISMATCH str %d %s: got %d ids, want %d\n",
                                         i, TOK_REF_STR[i], n, TOK_REF_NID[i]);
                failures++;
            }
        }
        if (ok == TOK_REF_N)
            printf("ref-diff   TIER 1: all %d strings match Qwen (%ld tokens, remapped ids)\n",
                   TOK_REF_N, toks);
        else
            printf("  FAIL ref-diff tier 1: %d/%d strings matched\n", ok, TOK_REF_N);
    }

    /* ── 2. ROUND-TRIP: encode then decode == original bytes ── */
    {
        int ok = 0;
        for (int i = 0; i < TOK_REF_N; i++) {
            uint32_t ids[256];
            uint8_t back[1024];
            int n = tok_encode_tab(&T, TOK_REF_STR[i], (uint32_t)TOK_REF_STRLEN[i], ids, 256);
            int m = tok_decode_tab(&T, ids, (uint32_t)n, back, sizeof back);
            if (n >= 0 && m == TOK_REF_STRLEN[i] &&
                memcmp(back, TOK_REF_STR[i], (size_t)m) == 0) ok++;
            else {
                if (failures < 6) printf("  ROUND-TRIP FAIL str %d: %d bytes back, want %d\n",
                                         i, m, TOK_REF_STRLEN[i]);
                failures++;
            }
        }
        if (ok == TOK_REF_N)
            printf("round-trip decode(encode(s)) == s for all %d strings\n", TOK_REF_N);
    }

    /* ── 3. CONTROL: corrupt one merge rank; the diff must catch it ── */
    {
        unsigned char *bad = malloc(TOK_TABLE_LEN);
        memcpy(bad, TOK_TABLE, TOK_TABLE_LEN);
        /* Make the pivotal merge of corpus[CTRL] never win (rank = 0xFFFFFFFF,
         * which the encoder's best-rank sentinel excludes by construction). */
        bad[TOK_REF_CTRL_RANK_OFF + 0] = 0xFF; bad[TOK_REF_CTRL_RANK_OFF + 1] = 0xFF;
        bad[TOK_REF_CTRL_RANK_OFF + 2] = 0xFF; bad[TOK_REF_CTRL_RANK_OFF + 3] = 0xFF;

        struct tok_table B;
        const char *be = tok_parse(bad, TOK_TABLE_LEN, &B);
        if (be) { printf("  FAIL control: corrupted table did not parse (%s)\n", be); failures++; }
        else {
            int i = TOK_REF_CTRL_STR;
            uint32_t ids[256];
            int n = tok_encode_tab(&B, TOK_REF_STR[i], (uint32_t)TOK_REF_STRLEN[i], ids, 256);
            if (ids_equal(ids, n, TOK_REF_IDS[i], TOK_REF_NID[i])) {
                printf("  FAIL control: corrupting a merge rank did NOT change str %d\n", i);
                failures++;
            } else {
                printf("control    corrupt 1 merge rank -> str %d re-tokenizes "
                       "(%d ids vs %d): gate catches it\n", i, n, TOK_REF_NID[i]);
            }
        }
        free(bad);
    }

    /* ── 4. MALFORMED TABLES (run under ASan to prove no over-read) ── */
    {
        printf("malformed  (each rejected, nothing read past the exact-size buffer)\n");
        const uint32_t LEN = TOK_TABLE_LEN;
        uint32_t off_ofs = rd32le(TOK_TABLE + 20);
        uint32_t blob_len = rd32le(TOK_TABLE + 28);
        uint32_t n_tokens = rd32le(TOK_TABLE + 8);

        /* truncated header (below 64 bytes) */
        expect_reject("truncated header", TOK_TABLE, 40);
        /* truncated body: header intact, sections don't fit */
        expect_reject("truncated body", TOK_TABLE, LEN - 100);

        unsigned char *m = malloc(LEN);

        memcpy(m, TOK_TABLE, LEN); m[0] ^= 0xFF;
        expect_reject("bad magic", m, LEN);

        memcpy(m, TOK_TABLE, LEN); m[4] = 2;               /* version 2 */
        expect_reject("bad version", m, LEN);

        memcpy(m, TOK_TABLE, LEN); m[16] += 8;             /* off_mrg tampered */
        expect_reject("bad merges offset", m, LEN);

        /* backwards offset: force the last offset below its predecessor */
        memcpy(m, TOK_TABLE, LEN);
        m[off_ofs + n_tokens * 4 + 0] = 0; m[off_ofs + n_tokens * 4 + 1] = 0;
        m[off_ofs + n_tokens * 4 + 2] = 0; m[off_ofs + n_tokens * 4 + 3] = 0;
        expect_reject("backwards offset", m, LEN);

        /* an offset that points past the blob */
        memcpy(m, TOK_TABLE, LEN);
        uint32_t past = blob_len + 1;
        m[off_ofs + 4 + 0] = (unsigned char)(past);       m[off_ofs + 4 + 1] = (unsigned char)(past >> 8);
        m[off_ofs + 4 + 2] = (unsigned char)(past >> 16); m[off_ofs + 4 + 3] = (unsigned char)(past >> 24);
        expect_reject("offset past blob", m, LEN);

        /* byte2id id out of range (>= n_tokens) */
        memcpy(m, TOK_TABLE, LEN);
        m[64 + 0] = (unsigned char)(n_tokens);       m[64 + 1] = (unsigned char)(n_tokens >> 8);
        m[64 + 2] = (unsigned char)(n_tokens >> 16); m[64 + 3] = (unsigned char)(n_tokens >> 24);
        expect_reject("byte2id out of range", m, LEN);

        free(m);
    }

    /* ── 5. max/truncation: dropping the tail at a segment boundary ── */
    {
        uint32_t ids[256];
        int full = tok_encode_tab(&T, TOK_REF_STR[0], (uint32_t)TOK_REF_STRLEN[0], ids, 256);
        uint32_t cut[8];
        int n = tok_encode_tab(&T, TOK_REF_STR[0], (uint32_t)TOK_REF_STRLEN[0], cut, 2);
        int prefix_ok = (n <= 2);
        for (int i = 0; i < n && prefix_ok; i++) if (cut[i] != ids[i]) prefix_ok = 0;
        if (full >= 0 && prefix_ok)
            printf("max-cap    encode(max=2) -> %d ids, an exact prefix of the full %d\n", n, full);
        else { printf("  FAIL max-cap: got %d ids, not a bounded prefix of %d\n", n, full); failures++; }
    }

    /* ── 1b. REFERENCE DIFF, tier 2 (LITERAL real Qwen ids, real 4 MB table) ── */
    {
        const char *dir = getenv("TOK_REAL_DIR");
        if (!dir) {
            printf("ref-diff   TIER 2: SKIPPED (set TOK_REAL_DIR to the dir holding the\n"
                   "           real Qwen tok.bin to match the LITERAL Qwen ids over the\n"
                   "           full 151387-merge table)\n");
        } else {
            char path[1024];
            snprintf(path, sizeof path, "%s/tok.bin", dir);
            FILE *fp = fopen(path, "rb");
            if (!fp) { printf("  FAIL tier 2: cannot open %s\n", path); failures++; }
            else {
                fseek(fp, 0, SEEK_END); long sz = ftell(fp); fseek(fp, 0, SEEK_SET);
                unsigned char *buf = malloc((size_t)sz);
                if (fread(buf, 1, (size_t)sz, fp) != (size_t)sz) { printf("  FAIL tier 2: short read\n"); failures++; }
                else {
                    struct tok_table R;
                    const char *re = tok_parse(buf, (uint32_t)sz, &R);
                    if (re) { printf("  FAIL tier 2: real table rejected: %s\n", re); failures++; }
                    else {
                        int ok = 0; long toks = 0;
                        for (int i = 0; i < TOK_REF_N; i++) {
                            uint32_t idbuf[256];
                            int n = tok_encode_tab(&R, TOK_REF_STR[i], (uint32_t)TOK_REF_STRLEN[i], idbuf, 256);
                            if (n >= 0 && ids_equal(idbuf, n, TOK_REAL_IDS[i], TOK_REAL_NID[i])) { ok++; toks += n; }
                            else {
                                if (failures < 8) printf("  TIER2 MISMATCH str %d %s: got %d, want %d\n",
                                                         i, TOK_REF_STR[i], n, TOK_REAL_NID[i]);
                                failures++;
                            }
                        }
                        if (ok == TOK_REF_N)
                            printf("ref-diff   TIER 2: all %d strings match LITERAL Qwen ids "
                                   "(%ld tokens, real 4 MB table: %u tokens/%u merges)\n",
                                   TOK_REF_N, toks, R.n_tokens, R.n_merges);
                    }
                }
                free(buf); fclose(fp);
            }
        }
    }

    printf("\nfailures  %d\n", failures);
    printf(failures ? "FAILED\n" : "PASS\n");
    return failures ? 1 : 0;
}
